server:
  port: 8080

spring:
  application:
    name: spring-boot-microservice
  thymeleaf:
    cache: false

# Actuator - expose health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
